Dev 12.0 afc 2790
vertelab/odoo-mail pull request #80
Opened 2021-09-29 12:09 UTC by berhr

Översättning av .PO-fil till svenska

2021-09-29 13:05 UTC, nils-vertel requested changes

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +"Last-Translator: <>\n"
Add your name here

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Autoresponder : Uppdatera autoresponderstatus för att sluta när den är klar."
The english version uses A on autoresponder, consider using capital A on the swedish version as well.

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Autoresponder postrevision"
Capital Case on the english version but not in the swedish version?

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Autoresponder namn"
Capital Case on the english version but not in the swedish version?

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Autoresponder segment"
Capital Case on the english version but not in the swedish version?

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Studsat förhållande"
Capital Case on the english version but not in the swedish version?

2021-09-29 13:05 UTC, nils-vertel commented on mass_mailing_autoresponder/i18n/sv_SE.po
> +msgstr "Antal åtgärder"
Capital Case on the english version but not in the swedish version?

2021-09-30 08:11 UTC, HazeLidman commented
okay, mergat

2021-09-30 08:11 UTC, merged